---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: summer-of-code
    labels:
        app: beginner.codes-soc
spec:
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 2
            maxUnavailable: 50%
    selector:
        matchLabels:
            app: beginner.codes-soc
            tier: frontend
    replicas: 1
    template:
        metadata:
            labels:
                app: beginner.codes-soc
                tier: frontend
        spec:
            containers:
              - name: fastapi-site
                image: zzmmrmn/summer-of-code:36
                ports:
                  - containerPort: 8000
                resources:
                    requests:
                        cpu: 100m
                env:
                    - name: SOC_DISCORD_CLIENT_SECRET
                      valueFrom:
                        secretKeyRef:
                            name: discord.client.secret
                            key: client_secret.txt
