---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: summer-of-code
    labels:
        app: beginner.codes-soc
spec:
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 2
            maxUnavailable: 50%
    selector:
        matchLabels:
            app: beginner.codes-soc
            tier: frontend
    replicas: 1
    template:
        metadata:
            labels:
                app: beginner.codes-soc
                tier: frontend
        spec:
            containers:
              - name: fastapi-site
                image: zzmmrmn/summer-of-code:<IMAGE_VERSION>
                ports:
                  - containerPort: 8000
                resources:
                    requests:
                        cpu: 100m
                env:
                    - name: SOC_DB_HOST
                      valueFrom:
                        configMapKeyRef:
                            name: soc-postgres-config
                            key: soc.db.host
                    - name: SOC_DB_PORT
                      valueFrom:
                        configMapKeyRef:
                            name: soc-postgres-config
                            key: soc.db.port
                    - name: SOC_DB_DATABASE
                      valueFrom:
                        configMapKeyRef:
                            name: soc-postgres-config
                            key: soc.db.database
                    - name: SOC_DB_USERNAME
                      valueFrom:
                        configMapKeyRef:
                            name: soc-postgres-config
                            key: soc.db.username
                    - name: SOC_DB_PASSWORD
                      valueFrom:
                        configMapKeyRef:
                            name: soc-postgres-config
                            key: soc.db.password
                    - name: SOC_DB_DRIVER
                      valueFrom:
                        configMapKeyRef:
                            name: soc-postgres-config
                            key: soc.db.driver
                    - name: SOC_DISCORD_CLIENT_SECRET
                      valueFrom:
                        secretKeyRef:
                            name: discord.client.secret
                            key: client_secret.txt
